services:
  schaublin-dashboard:
    build: NPM-Folder/
    container_name: schaublin-dashboard
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  rpm-meter:
    build: RPM-Meter/
    container_name: rpm-meter
    ports:
      - "8000:8000"
    restart: unless-stopped

  
