services:
  schaublin-dashboard:
    build: NPM-Folder/
    container_name: schaublin-dashboard
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  rpm-meter:
    build: RPM-Meter/
    container_name: rpm-meter
    ports:
      - "8000:8000"
    restart: unless-stopped
    privileged: true  # Gebe dem Container privilegierten Zugriff auf das Host-System
    devices:
      - "/dev/gpiomem:/dev/gpiomem"  # Gib Zugriff auf das GPIO-Memory Device
      - "/dev/gpiochip0:/dev/gpiochip0"  
      - "/dev/gpiochip4:/dev/gpiochip4"  
    volumes:
      - /sys/class/gpio:/sys/class/gpio:rw  # Ermögliche das Schreiben in GPIO-Dateien
    environment:
      - PYTHONUNBUFFERED=1
